[project]
name = "massband"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jax>=0.6.1",
    "laufband>=0.1.3",
    "lazy-loader>=0.4",
    "znh5md>=0.4.5",
    "zntrack>=0.8.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
